### ISSUE TITLE
Install Failure: No *.brs script files found.

### ISSUE THREAD

**Issue by bengalih** [llamasoft/RootMyRoku#3]
When uploading via Developer UI:
"Install Failure: No *.brs script files found."

TCL 55S20
9.4.0 - Build 4210-93

Not sure where to go from here. 
- Is this version unsupported?
- If so, is it possible it will be?
- I was hoping mainly to be able to enable change some HDR settings that are not available on my model.  Would I be able to do that with this exploit if it worked?

**Comment by elliwigy** [comment]
Hello,

I am receiving the same error. 

Roku TV C209X
Hisense Model 43R6+
9.4.0 - Build 4210-4
"Install Failure: No *.brs script files found."

I will assume this means it is patched unless it is said otherwise. Unfortunately my newer TV already has 10.0.0 on it so I won't even bother there.

**Comment by elliwigy** [comment]
Hello,

I noticed the latest release/zip only had a manifest and folders were empty. I then took the hello-world.zip to compare it and saw what I needed to put in the rootmyroku zip. I then opened the source zip and went to the local folder and essentially took the 3 folders and the manifest and made a zip. I was then able to upload and install it but unfortunately now it displays this message:

"If you're seeing this, the NFS mount failed or the exploit was patched. :("

By this I am assuming it is not compatible on my TV with build 9.4.0 4210-4. Of course if anyone thinks something else is the issue then I am up for any testing but will stick with my original assumption that it is patched on my device.

But just an FYI, the zip on the release page only contains 3 empty folders and a manifest file which I do not think was intended since it is not able to be installed as is.

Thanks

**Comment by elliwigy** [comment]
I am an idiot lol.. You clearly state it should work on any device on 9.4.0 4200 or lower and both mine and original person who opened this ticket are both on 4210. I should have read more closely before commenting haha, you can ignore my posts. There is no issue since our versions are not in the compatibilty range.
