### ISSUE TITLE
Can't upgrade to 9.4 from 9.2.2

### ISSUE THREAD

**Issue by keshto** [llamasoft/RootMyRoku#8]
With newer TVs that ship with 9.2.2, the exploit does not seem to work and when trying to force an update to the tested 9.4 version there is a message showing that one cannot downgrade...?

**Comment by llamasoft** [comment]
Are you _sure_ you're on version 9.2.2 and not 10.2.2?  RokuOS 9.2 was released a _long_ time ago and I don't imagine that _new_ TVs ship with it.

You can check your full version number and build number by pulling up the Roku secret menu.

**Comment by keshto** [comment]
I am pretty sure. Please see attached image.
![tv](https://user-images.githubusercontent.com/766237/145309190-41e155f4-5fce-48d6-8e84-76144ba2f9da.jpeg)

**Comment by llamasoft** [comment]
Huh.  I stand corrected.  That's actually _very_ surprising.
I know most Roku TVs have the ability to apply firmware updates via USB drives, but unless you happen to have the 9.4.0 update files for your exact model then you're out of luck.

The other snag is that even if they ship factory fresh with an exploitable version, the initial TV setup _requires_ downloading and applying a firmware update before you can continue.  I also believe activating developer mode forces an update check as well.  Currently, I'm not aware of any ways to bypass the initial update requirement. :(

**Comment by llamasoft** [comment]
That's odd.  The last time I took a look at this, attempting to do the initial setup while blocking access to Roku's update servers simply caused the initial setup to fail.  It put me in a loop of "need to update" and "failed to update".

What I find incredibly strange is that your build date is actually very recent.  I know Roku released patched versions of their older firmwares after this exploit was released, but that doesn't explain why they'd still use a _patched_ 9.2 image the factory default image instead of something newer like 9.4 or 10.

My best guess is that the update is comparing build dates instead of version numbers.

**Comment by keshto** [comment]
You can get through the initial setup it is just a timing thing. You have to not reject the update but let it fail with a timeout and enable access soon as it times out because they check after. 

The build time vs version makes sense. The updates are sha1sum and then attested by roku so cant really change the built time (plus dont know where to start with that since dont know the update package format)

Have any ideas on what I should do?

**Comment by llamasoft** [comment]
Hmm, I'm curious about the upgrade skip.  Do you mind emailing me directly so we can discuss this further?  You can contact me at llamasoft@rm-rf.email
